name: "Main workflow"

on:
  push:
    paths:
      - "pages/**"
      - "components/**"
      - "styles/**"
    branches:
      - main
  pull_request:
    paths:
      - "pages/**"
      - "components/**"
      - "styles/**"

jobs:
  format:
    name: "Format code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettify code 
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,md}
          only_changed: True

      - name: Fetch dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Initialize waypoint
        id: init
        uses: hashicorp/action-setup-waypoint
        with:
          version: '0.1.0'

      - run: waypoint init
      - run: waypoint build
      - run: waypoint deploy

      - name: Waypoint release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: waypoint release


        