CREATE TABLE "User" (
  "id" uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text,
  "mobile" text,
  "firstName" text,
  "lastName" text
);

CREATE TABLE "ServiceStatus" (
  "id" uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "description" TEXT
);

CREATE TYPE payment_status AS ENUM('PENDING', 'FAILED', 'COMPLETED');

CREATE TABLE "UserCheckin" (
  "id" uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" uuid,
  "expectedCheckinTime" timestamp,
  "expectedCheckoutTime" timestamp,
  "actualCheckinTime" timestamp,
  "actualCheckoutTime" timestamp,
  CONSTRAINT "FK_UserCheckin.userId"
    FOREIGN KEY ("userId")
      REFERENCES "User"("id")
);

CREATE TABLE "PaymentDetail" (
  "id" uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userCheckinId" uuid,
  "paymentMode" text,
  "paymentAmount" FLOAT,
  "paymentStatus" payment_status,
  "cancelled" BOOLEAN,
  CONSTRAINT "FK_PaymentDetail.userCheckinId"
    FOREIGN KEY ("userCheckinId")
      REFERENCES "UserCheckin"("id")
);

CREATE TABLE "Service" (
  "id" uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "description" TEXT,
  "slug" text,
  "timeRequired" int,
  "carParkLimitPerHour" int,
  "cost" FLOAT,
  "enabled" BOOLEAN
);

CREATE TABLE "UserCheckinService" (
  "id" uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userCheckinId" uuid,
  "serviceId" uuid,
  CONSTRAINT "FK_UserCheckinService.serviceId"
    FOREIGN KEY ("serviceId")
      REFERENCES "Service"("id"),
  CONSTRAINT "FK_UserCheckinService.userCheckinId"
    FOREIGN KEY ("userCheckinId")
      REFERENCES "UserCheckin"("id")
);

CREATE TABLE "UserService" (
  "id" uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userCheckinServiceId" uuid,
  "serviceStatusId" uuid,
  CONSTRAINT "FK_UserService.userCheckinServiceId"
    FOREIGN KEY ("userCheckinServiceId")
      REFERENCES "UserCheckinService"("id"),
  CONSTRAINT "FK_UserService.serviceStatusId"
    FOREIGN KEY ("serviceStatusId")
      REFERENCES "ServiceStatus"("id")
);


